from typing import Protocol

from sqlalchemy.engine import Connection

from ..models import DataSource


class CatalogProvider(Protocol):
    source: DataSource

    def probe_sql(self) -> str: ...

    def stage_names(self) -> list[str]: ...

    def schema_query(self) -> str: ...

    def schema_names(self, connection: Connection) -> list[str]: ...

    def table_names(self, connection: Connection, schema_name: str) -> list[str]: ...

    def view_names(self, connection: Connection, schema_name: str) -> list[str]: ...

    def columns(self, connection: Connection, schema_name: str, table_name: str) -> list[dict]: ...

    def procedures(self, connection: Connection, schema_name: str) -> list[dict]: ...

    def select_permissions(self, connection: Connection, schema_name: str) -> dict[str, dict]: ...
